apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  volumes: 
    - name: web-volume
      hostPath: 
        path: /tmp/webdata
        type: Directory
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: web-volume
          mountPath: /usr/share/nginx/htmlc

